config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/profiles', to: 'profiles#helper_list', as: 'profiles'
  get '/profiles/:id', to: 'profiles#helper_details', as: 'profile'

  resources :bookings, only: [:show] do
    resources :reviews, only: [:create]
  end

  post "/profiles/:id/bookings", to: "bookings#create", as: 'booking_create'
  get "/bookings/:id/edit_tasks", to: "bookings#edit_tasks", as: 'tasks'
  get "/bookings/:id/edit_validation", to: "bookings#edit_validation", as: 'validation'
  patch "/bookings/:id/tasks", to: "bookings#update_task", as: 'booking_update_tasks'
  patch "/bookings/:id/validation", to: "bookings#update_validation", as: 'booking_update_validation'
  patch "/bookings/:id/status", to: "bookings#update_status", as: 'status_change'
  get "/senior", to: "pages#senior", as: 'senior'
  get "/helper", to: "pages#helper", as: 'helper'
  get 'calendars/show', to:"calendars#show", as: 'calendar'
  post "calendars/sch_generate", to: "calendars#sch_generate", as: 'sch_generate'
  get "/favoris", to: "favoris#index", as: 'favoris_index'
  post "/favoris", to: "favoris#create"
  delete "/favoris/:id", to: "favoris#destroy",as: 'favoris_destroy'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "sekoya_logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if !current_user.photo.present?%>
            <%= cl_image_tag("default_photo.png", :default_image=>"default_photo", :gravity=>"face", :width=>50, :crop=>"thumb", data: { toggle: "dropdown" })%>
          <% else %>
            <%= cl_image_tag current_user.photo.key, class: "avatar avatar-senior-small dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right seko-card" aria-labelledby="navbarDropdown">
            <% if current_user.role == "helper" %>
              <%= link_to "Tableau de bord", helper_path, class: "dropdown-item" %>
              <%= link_to "Calendrier", calendar_path, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Tableau de bord", senior_path, class: "dropdown-item" %>
              <%= link_to "Mes favoris", favoris_index_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item seko-flex">
<!--        <%= link_to "Devenez aide à domicile", new_user_session_path, class: "nav-link col-6 seko-button btn" %>
          <%= link_to "S'inscrire", new_user_session_path, class: "nav-link" %> -->
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link col-12" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>