config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/profiles', to: 'profiles#helper_list', as: 'profiles'
  get '/profiles/:id', to: 'profiles#helper_details', as: 'profile'

  resources :bookings, only: [:show] do
    resources :reviews, only: [:create]
  end

  post "/profiles/:id/bookings", to: "bookings#create", as: 'booking_create'
  get "/bookings/:id/edit_tasks", to: "bookings#edit_tasks", as: 'tasks'
  get "/bookings/:id/edit_validation", to: "bookings#edit_validation", as: 'validation'
  patch "/bookings/:id/tasks", to: "bookings#update_task", as: 'booking_update_tasks'
  patch "/bookings/:id/validation", to: "bookings#update_validation", as: 'booking_update_validation'
  patch "/bookings/:id/status", to: "bookings#update_status", as: 'status_change'
  get "/senior", to: "pages#senior", as: 'senior'
  get "/helper", to: "pages#helper", as: 'helper'
  get 'calendars/show', to:"calendars#show", as: 'calendar'
  post "calendars/sch_generate", to: "calendars#sch_generate", as: 'sch_generate'
  get "/favoris", to: "favoris#index", as: 'favoris_index'
  post "/favoris", to: "favoris#create"
  delete "/favoris/:id", to: "favoris#destroy",as: 'favoris_destroy'

end

app/views/pages/_bonjour.html.erb
<% if current_user.family_last_name.present? %>
<div class="">
    <h1 style="color: #1E80FC;"> <%= "Bonjour famille #{current_user.family_last_name} !" %> </h1>
</div>
<% else  %>
<div class="">
    <h1 style="color: #1E80FC;"> <%= "Bonjour famille #{current_user.last_name} !" %> </h1>
</div>
<% end %>

app/views/pages/_colorstatus.html.erb
<% if booking.status == "pending" %>
    <span style='color: orange;'>en attente</span>
<% elsif booking.status == "accepté" %>
    <span style='color: green;'><%= "accepté" %></span>
<% else %>
    <span style='color: red;'><%= booking.status %></span>
<% end %>

app/views/pages/_favoris.html.erb
<% unless helpers.include?(booking.helper) %>
    <%= link_to "♡", favoris_path(booking: booking, path: path),
    method: :post, class: "btn seko-small-button m-2" %>
<% else  %>
    <%= link_to "♥", favoris_destroy_path(booking, path: path),
    method: :delete, class: "btn seko-small-button m-2" %>
<% end  %>

app/views/pages/_wallet.html.erb
<div>
    <h1>Porte-monnaie</h1>
    <p>Gérez vos transactions et votre compte Sekoya.</p>
</div>

app/views/pages/helper.html.erb
<div class="col-10">

  <!-- Next booking, Wallet and Planning -->
  <div class="seko-flex">
    <div class="col-6">
      <div>
        <h1 style="color: #1E80FC;"><%= "Bonjour #{current_user.first_name} !" %></h1>
      </div>

      <!-- Next booking -->
<!--       <div>
        <h2 class="mb-3">Prochaine prestation</h2>
        <div class="seko-card p-3">
          <% if @booking_next.nil? %>
            <p>Vous n'avez pas de prestation à venir</p>
          <% else %>
           <%= link_to booking_path(@booking_next) do %>
          <div class="seko-flex">
            <div>
              <% if !@booking_next.senior.photo.present? %>
                <%= cl_image_tag("default_photo.png", :default_image=>"default_photo", :gravity=>"face", :width=>100, :crop=>"thumb") %>
              <% else %>
                <%= cl_image_tag @booking_next.senior.photo.key, class: "avatar avatar-senior" %>
              <% end %>
            </div>
            <div class="col-6">
              <h4><%= @booking_next.senior.first_name %> <%= @booking_next.senior.last_name %></h4>
              <p>Le <%= @booking_next.date.strftime("%d/%m/%Y") %></p>
              <p>De <%= @booking_next.start_time.strftime("%R") %> à <%= @booking_next.end_time.strftime("%R") %></p>
            </div>
            <div>
              <h4>Prix : <%= ((@booking_next.helper.price)*((@booking_next.end_time  - @booking_next.start_time)/3600).to_i).to_i %>€</h4>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div> -->

    <!-- Wallet and Planning -->
<!--     <div class="col-6">
 -->      <!-- Wallet -->
<!--       <div class="seko-card p-2 text-center m-3">
        <%= render :partial => "wallet" %>
      </div> -->

      <!-- Planning -->
<!--       <a target="_blank" href="https://calendar.google.com/calendar/r">
      <div class="seko-card text-center p-2 m-3">
        <h1>Mon planning</h1>
        <p>Retouvez votre planning</p>
      </div>
      </a>
    </div>
  </div> -->

  <!-- Bookings -->
<!--   <div class="ml-3 mr-3">
    <div>
      <h2 class="mt-3">Prestations</h2>
    </div> -->

    <div>
      <!-- Navbar bookings -->
      <ul class="nav" id="myTab" role="tablist">
        <!-- Navbar today bookings -->
        <li class="nav-item" role="presentation">
          <a class="nav-link active dashboard-nav-btn" id="week-tab" data-toggle="tab" href="#week" role="tab" aria-controls="week" aria-selected="true">Aujourd'hui</a>
        </li>
        <!-- Navbar pending bookings -->
        <li class="nav-item" role="presentation">
          <a class="nav-link dashboard-nav-btn" id="pending-tab" data-toggle="tab" href="#pending" role="tab" aria-controls="pending" aria-selected="false">En attente (<%= @pending.length %>)</a>
        </li>
        <!-- Navbar futur bookings -->
        <li class="nav-item" role="presentation">
          <a class="nav-link dashboard-nav-btn" id="futur-tab" data-toggle="tab" href="#futur" role="tab" aria-controls="futur" aria-selected="false">A venir</a>
        </li>
        <!-- Navbar historic bookings -->
        <li class="nav-item" role="presentation">
          <a class="nav-link dashboard-nav-btn" id="historique-tab" data-toggle="tab" href="#historique" role="tab" aria-controls="historique" aria-selected="false">Historique</a>
        </li>
      </ul>

      <div class="tab-content" id="myTabContent">
        <!-- Today bookings -->
        <div class="tab-pane fade show active" id="week" role="tabpanel" aria-labelledby="week-tab">
          <% @helper_day.each do |booking| %>
            <%= link_to booking_path(booking) do%>

              <div class="seko-card pl-3 mb-3 pr-4 seko-flex senior-long-block">
                <div class="seko-flex">
                  <div>
                    <% if !booking.senior.photo.present? %>
                      <%= cl_image_tag("default_photo.png", class: "avatar-mobile", :default_image=>"default_photo", :gravity=>"face", :width=>100, :crop=>"thumb") %>
                    <% else %>
                      <%= cl_image_tag booking.senior.photo.key, class: "avatar avatar-senior avatar-mobile" %>
                    <% end %>
                  </div>

                  <div class="m-4 pr-4 border-right border-left pl-4 seko-part-card">
                    <h4><%= booking.senior.first_name %> <%= booking.senior.last_name %></h4>
                    <p>Le <%= booking.date.strftime("%d/%m/%Y") %></p>
                    <p>De <%= booking.start_time.strftime("%R") %>h à <%= booking.end_time.strftime("%R") %>h</p>
                    <p><%= render :partial => "colorstatus", locals: { booking: booking } %></p>
                  </div>

                  <div class="m-4 missions pr-4 border-right seko-part-card">
                    <h4>Activités :</h4>
                    <% booking.tasks.each do |task| %>
                      <li><%= task.name %></li>
                    <% end %>
                  </div>
                  <div class="m-4 missions seko-part-card-price">
                    <h4>Prix : <%= ((booking.helper.price)*((booking.end_time  - booking.start_time)/3600).to_i).to_i %>€</h4>
                    <p><%= booking.helper.price %>€ par heure</p>
                  </div>
                </div>
                <div class="col-3 missions seko-cancel-area border-left m-4 pl-4">
                  <button class="btn seko-button">Visualiser la réservation</button>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

        <!-- Pending bookings -->
        <div class="tab-pane fade" id="pending" role="tabpanel" aria-labelledby="pending-tab">
          <% @pending.each do |booking| %>
            <%= link_to booking_path(booking) do%>
              <div class="seko-card pl-3 mb-3 pr-4 seko-flex senior-long-block">
                <div class="seko-flex">
                  <div>
                    <% if !booking.senior.photo.present?%>
                      <%= cl_image_tag("default_photo.png", class: "avatar-mobile", :default_image=>"default_photo", :gravity=>"face", :width=>100, :crop=>"thumb") %>
                    <% else %>
                      <%= cl_image_tag booking.senior.photo.key, class: "avatar avatar-senior avatar-mobile" %>
                    <% end %>
                  </div>
                  <div class="m-4 pr-4 border-right border-left pl-4 seko-part-card">
                    <h4><%= booking.senior.first_name %> <%= booking.senior.last_name %></h4>
                    <p>Le <%= booking.date.strftime("%d/%m/%Y") %></p>
                    <p>De <%= booking.start_time.strftime("%R") %>h à <%= booking.end_time.strftime("%R") %>h</p>
                    <p><%= render :partial => "colorstatus", locals: { booking: booking } %></p>
                  </div>
                  <div class="m-4 missions pr-4 border-right seko-part-card">
                    <h4>Activités :</h4>
                    <% booking.tasks.each do |task| %>
                      <li><%= task.name %></li>
                    <% end %>
                  </div>
                  <div class="m-4 missions pt-1 seko-part-card-price">
                    <h4>Prix : <%= ((booking.helper.price)*((booking.end_time  - booking.start_time)/3600).to_i).to_i %>€</h4>
                    <p><%= booking.helper.price %>€ par heure</p>
                  </div>
                </div>
                <div class="col-3 missions seko-cancel-area border-left m-4 pl-4">
                  <%= link_to "Accepter la demande", status_change_path(booking, status: "accepté"),
                  method: :patch, data: { confirm: 'Voulez vous accepter cette réservation??' }, class: "btn seko-button mb-3" %>
                  <%= link_to "Refuser la demande", status_change_path(booking, status: "refusé"),
                  method: :patch, data: { confirm: 'Voulez vous refuser cette réservation?' }, class: "btn seko-cancel-button" %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

        <!-- Futur bookings -->
        <div class="tab-pane fade" id="futur" role="tabpanel" aria-labelledby="futur-tab">
          <% @avenir.each do |booking| %>
            <%= link_to booking_path(booking) do%>
              <div class="seko-card pl-3 mb-3 pr-4 seko-flex senior-long-block">
                <div class="seko-flex">
                  <div>
                    <% if !booking.senior.photo.present? %>
                      <%= cl_image_tag("default_photo.png", class: "avatar-mobile", :default_image=>"default_photo", :gravity=>"face", :width=>100, :crop=>"thumb") %>
                    <% else %>
                      <%= cl_image_tag booking.senior.photo.key, class: "avatar avatar-senior avatar-mobile" %>
                    <% end %>
                  </div>
                  <div class="m-4 pr-4 border-right border-left pl-4 seko-part-card">
                    <h4><%= booking.senior.first_name %> <%= booking.senior.last_name %></h4>
                    <p>Le <%= booking.date.strftime("%d/%m/%Y") %></p>
                    <p>De <%= booking.start_time.strftime("%R") %>h à <%= booking.end_time.strftime("%R") %>h</p>
                    <p><%= render :partial => "colorstatus", locals: { booking: booking } %></p>
                  </div>
                  <div class="m-4 missions pr-4 border-right seko-part-card">
                    <h4>Activités :</h4>
                    <% booking.tasks.each do |task| %>
                      <li><%= task.name %></li>
                    <% end %>
                  </div>
                  <div class="m-4 missions seko-part-card-price">
                    <h4>Prix : <%= ((booking.helper.price)*((booking.end_time  - booking.start_time)/3600).to_i).to_i %>€</h4>
                    <p><%= booking.helper.price %>€ par heure</p>
                  </div>
                </div>
                <div class=" col-3 missions seko-cancel-area seko-part-card border-left m-4 pl-4">
                  <% if booking.date >= Date.today + 7 %>
                    <%= link_to "Annuler cette réservation", status_change_path(booking, status: "refusé"),
                    method: :patch, data: { confirm: 'Voulez vous annuler cette réservation??' }, class: "btn seko-cancel-button" %>
                  <% else %>
                    <button class="btn seko-under-seven-btn">Vous ne pouvez plus annuler cette réservation</button>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

        <!-- Historic bookings -->
        <div class="tab-pane fade" id="historique" role="tabpanel" aria-labelledby="historique-tab">
          <% @historique.each do |booking| %>
            <%= link_to booking_path(booking) do%>
              <div class="seko-card pl-3 mb-3 pr-4 seko-flex senior-long-block">
                <div class="seko-flex">
                  <div>
                    <% if !booking.senior.photo.present? %>
                      <%= cl_image_tag("default_photo.png", class: "avatar-mobile", :default_image=>"default_photo", :gravity=>"face", :width=>100, :crop=>"thumb") %>
                    <% else %>
                      <%= cl_image_tag booking.senior.photo.key, class: "avatar avatar-senior avatar-mobile" %>
                    <% end %>
                  </div>
                  <div class="m-4 pr-4 border-right border-left pl-4 seko-part-card">
                    <h4><%= booking.senior.first_name %> <%= booking.senior.last_name %></h4>
                    <p>Le <%= booking.date.strftime("%d/%m/%Y") %></p>
                    <p>De <%= booking.start_time.strftime("%R") %>h à <%= booking.end_time.strftime("%R") %>h</p>
                    <p><%= render :partial => "colorstatus", locals: { booking: booking } %></p>
                  </div>
                  <div class="m-4 missions pr-4 border-right seko-part-card">
                    <h4>Activités :</h4>
                    <% booking.tasks.each do |task| %>
                      <li><%= task.name %></li>
                    <% end %>
                  </div>
                  <div class="m-4 missions seko-part-card-price">
                    <h4>Prix : <%= ((booking.helper.price)*((booking.end_time  - booking.start_time)/3600).to_i).to_i %>€</h4>
                    <p><%= booking.helper.price %>€ par heure</p>
                  </div>
                </div>
                <div class="col-3 missions seko-cancel-area seko-part-card border-left m-4 pl-4">
                  <button class="btn seko-button mb-2">Détails de la prestation</button>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/pages/senior.html.erb
<div class="col-10">
  <div class="seko-flex">
    <div class="col-6">
      <div>
        <%= render :partial => "bonjour" %>
      </div>
<!--       <div>
        <h2 class="mb-3">Prochaine prestation</h2>
        <div class="seko-card p-2">
          <% if @booking_next.nil? %>
          <p>Vous n'avez pas de prestation à venir</p>
          <% else %>
          <%= link_to booking_path(@booking_next) do %>
          <div class="seko-flex">
            <div>
              <% if !@booking_next.helper.photo.present? %>
                <%= cl_image_tag("default_photo.png", :default_image=>"default_photo", :gravity=>"face", :width=>100, :crop=>"thumb") %>
              <% else %>
                <%= cl_image_tag @booking_next.helper.photo.key, class: "avatar avatar-senior" %>
              <% end %>
            </div>
            <div class="col-10">
              <div class="seko-flex">
                <h4><%= @booking_next.helper.first_name %> <%= @booking_next.helper.last_name %></h4>
                <p>Le <%= @booking_next.date.strftime("%d/%m/%Y") %></p>
                <p>De <%= @booking_next.start_time.strftime("%R") %>h à <%= @booking_next.end_time.strftime("%R") %>h</p>
                <div>
                  <%= render :partial => "favoris", locals: { booking: @booking_next, helpers: @favoris_helper, path: "dashboard" } %>
                  <h4 class="mt-4">Prix : <%= ((@booking_next.helper.price)*((@booking_next.end_time  - @booking_next.start_time)/3600).to_i).to_i %>€</h4>
                </div>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
      </div>
    </div>
  </div>
  <div class="col-6">
    <div class="seko-card p-2 text-center m-3">
        <%= render :partial => "wallet" %>
    </div>
    <div class="seko-card text-center p-2 m-3">
        <%= link_to favoris_index_path do%>
        <h1>Mes favoris</h1>
        <p>Retouvez vos helpers préférés.</p>
        <% end %>
    </div>
  </div>
</div>
<div class="ml-3 mr-3">
    <div>
      <h2 class="mt-2">Prestations</h2>

    </div> -->
    <div>
      <ul class="nav" id="myTab" class="col-12" role="tablist">
        <li class="nav-item" role="presentation">
          <a class="nav-link active dashboard-nav-btn" id="week-tab" data-toggle="tab" href="#week" role="tab" aria-controls="week" aria-selected="true">Cette semaine</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link dashboard-nav-btn" id="pending-tab" data-toggle="tab" href="#pending" role="tab" aria-controls="pending" aria-selected="false">En attente (<%= @pending.length %>)</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link dashboard-nav-btn" id="futur-tab" data-toggle="tab" href="#futur" role="tab" aria-controls="futur" aria-selected="false">A venir</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link dashboard-nav-btn" id="historique-tab" data-toggle="tab" href="#historique" role="tab" aria-controls="historique" aria-selected="false">Historique</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="week" role="tabpanel" aria-labelledby="week-tab">
          <% @senior_week.each do |booking| %>
          <%= link_to booking_path(booking) do%>
          <div class="seko-card pl-3 mb-3 pr-4 seko-flex senior-long-block">
            <div class="seko-flex">
              <div>
                <% if !booking.helper.photo.present? %>
                  <%= cl_image_tag("default_photo.png", class: "avatar-mobile", :default_image=>"default_photo", :gravity=>"face", :width=>100, :crop=>"thumb") %>
                <% else %>
                  <%= cl_image_tag booking.helper.photo.key, class: "avatar avatar-senior avatar-mobile" %>
                <% end %>
              </div>

              <div class="m-4 pr-4 border-right border-left pl-4 seko-part-card">
                <h4><%= booking.helper.first_name %> <%= booking.helper.last_name %></h4>
                <p>Le <%= booking.date.strftime("%d/%m/%Y") %></p>
                <p>De <%= booking.start_time.strftime("%R") %>h à <%= booking.end_time.strftime("%R") %>h</p>
                <p><%= render :partial => "colorstatus", locals: { booking: booking } %></p>
              </div>

              <div class="mt-4 missions pr-2 border-right seko-part-card">
                <h4>Activités :</h4>
                <% booking.tasks.each do |task| %>
                <li><%= task.name %></li>
                <% end %>
              </div>
              <div class="mt-4 missions ml-3 seko-part-card-price">
                <h4>Prix : <%= ((booking.helper.price)*((booking.end_time  - booking.start_time)/3600).to_i).to_i %>€</h4>
                <p><%= booking.helper.price %>€ par heure</p>
              </div>
              <div>
              </div>
            </div>
            <div class="col-3 missions seko-cancel-area border-left pl-4 m-4">
            <%= link_to "Profil de l'aidant", profile_path(booking.helper), class: "btn seko-button" %>
            </div>
            <div class="missions">
              <%= render :partial => "favoris", locals: { booking: booking, helpers: @favoris_helper, path: "dashboard" } %>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
        <div class="tab-pane fade" id="pending" role="tabpanel" aria-labelledby="pending-tab">
          <% @pending.each do |booking| %>
          <%= link_to booking_path(booking) do%>
          <div class="seko-card pl-3 mb-3 pr-4 seko-flex senior-long-block">
            <div class="seko-flex">
              <div>
                <% if !booking.helper.photo.present? %>
                  <%= cl_image_tag("default_photo.png", class: "avatar-mobile", :default_image=>"default_photo", :gravity=>"face", :width=>100, :crop=>"thumb") %>
                <% else %>
                  <%= cl_image_tag booking.helper.photo.key, class: "avatar avatar-senior avatar-mobile" %>
                <% end %>
              </div>
              <div class="m-4 pr-4 border-right border-left pl-4 seko-part-card">
                <h4><%= booking.helper.first_name %> <%= booking.helper.last_name %></h4>
                <p>Le <%= booking.date.strftime("%d/%m/%Y") %></p>
                <p>De <%= booking.start_time.strftime("%R") %>h à <%= booking.end_time.strftime("%R") %>h</p>
                <p><%= render :partial => "colorstatus", locals: { booking: booking } %></p>
              </div>
              <div class="mt-4 missions pr-4 border-right seko-part-card">
                <h4>Activités :</h4>
                <% booking.tasks.each do |task| %>
                <li><%= task.name %></li>
                <% end %>
              </div>
              <div class="mt-4 missions ml-3 seko-part-card-price">
                <h4>Prix : <%= ((booking.helper.price)*((booking.end_time  - booking.start_time)/3600).to_i).to_i %>€</h4>
                <p><%= booking.helper.price %>€ par heure</p>
              </div>
            </div>
            <div class="col-3 missions seko-cancel-area border-left m-4 pl-4">
              <%= link_to "Profil de l'aidant", profile_path(booking.helper), class: "btn seko-button" %>
              <%= link_to "Annuler cette demande", status_change_path(booking, status: "annulé"),
              method: :patch, data: { confirm: 'Voulez vous annuler cette réservation?' }, class: "btn seko-cancel-button mt-4" %>
            </div>
            <div class="missions">
            <%= render :partial => "favoris", locals: { booking: booking, helpers: @favoris_helper, path: "dashboard" } %>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
        <div class="tab-pane fade" id="futur" role="tabpanel" aria-labelledby="futur-tab">
          <% @avenir.each do |booking| %>
          <%= link_to booking_path(booking) do%>
          <div class="seko-card pl-3 mb-3 pr-4 seko-flex senior-long-block">
            <div class="seko-flex">
              <div>
               <% if !booking.helper.photo.present? %>
                  <%= cl_image_tag("default_photo.png", class: "avatar-mobile", :default_image=>"default_photo", :gravity=>"face", :width=>100, :crop=>"thumb") %>
                <% else %>
                  <%= cl_image_tag booking.helper.photo.key, class: "avatar avatar-senior avatar-mobile" %>
                <% end %>
              </div>
              <div class="m-4 pr-4 border-right border-left pl-4 seko-part-card">
                <h4><%= booking.helper.first_name %> <%= booking.helper.last_name %></h4>
                <p>Le <%= booking.date.strftime("%d/%m/%Y") %></p>
                <p>De <%= booking.start_time.strftime("%R") %>h à <%= booking.end_time.strftime("%R") %>h</p>
                <p><%= render :partial => "colorstatus", locals: { booking: booking } %></p>
              </div>
              <div class="mt-4 missions pr-4 border-right seko-part-card">
                <h4>Activités :</h4>
                <% booking.tasks.each do |task| %>
                <li><%= task.name %></li>
                <% end %>
              </div>
              <div class="ml-3 missions mt-4 seko-part-card-price">
                <h4>Prix : <%= ((booking.helper.price)*((booking.end_time  - booking.start_time)/3600).to_i).to_i %>€</h4>
                <p><%= booking.helper.price %>€ par heure</p>
              </div>
            </div>
            <div class="missions col-3 seko-cancel-area seko-part-card border-left m-4 pl-4">
              <%= link_to "Profil de l'aidant", profile_path(booking.helper), class: "btn seko-button" %>
              <% if booking.date >= Date.today + 7 %>
              <%= link_to "Annuler cette réservation", status_change_path(booking, status: "annulé"),
              method: :patch, data: { confirm: 'Are you sure?' }, class: "btn seko-cancel-button mt-4" %>
              <% else %>
              <button class="btn seko-under-seven-btn mt-3">Vous ne pouvez plus annuler  cette réservation</button>
              <% end %>
            </div>
            <div class="missions">
            <%= render :partial => "favoris", locals: { booking: booking, helpers: @favoris_helper, path: "dashboard" } %>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
        <div class="tab-pane fade" id="historique" role="tabpanel" aria-labelledby="historique-tab">
              <% @historique.each do |booking| %>
              <%= link_to booking_path(booking) do%>
              <div class="seko-card pl-3 mb-3 pr-4 seko-flex senior-long-block">
                <div class="seko-flex">
                  <div>
                    <% if !booking.helper.photo.present? %>
                      <%= cl_image_tag("default_photo.png", class: "avatar-mobile", :default_image=>"default_photo", :gravity=>"face", :width=>100, :crop=>"thumb") %>
                    <% else %>
                      <%= cl_image_tag booking.helper.photo.key, class: "avatar avatar-senior avatar-mobile" %>
                    <% end %>
                  </div>
                  <div class="m-4 pr-4 border-right border-left pl-4 seko-part-card">
                    <h4><%= booking.helper.first_name %> <%= booking.helper.last_name %></h4>
                    <p>Le <%= booking.date.strftime("%d/%m/%Y") %></p>
                    <p>De <%= booking.start_time.strftime("%R") %>h à <%= booking.end_time.strftime("%R") %>h</p>
                    <p><%= render :partial => "colorstatus", locals: { booking: booking } %></p>
                  </div>
                  <div class="mt-4 missions pr-4 border-right seko-part-card">
                    <h4>Activités :</h4>
                    <% booking.tasks.each do |task| %>
                    <li><%= task.name %></li>
                    <% end %>
                  </div>
                  <div class="ml-3 missions mt-4 seko-part-card-price">
                    <h4>Prix : <%= ((booking.helper.price)*((booking.end_time  - booking.start_time)/3600).to_i).to_i %>€</h4>
                    <p><%= booking.helper.price %>€ par heure</p>
                  </div>
                </div>
                <div class="col-3 missions seko-cancel-area seko-part-card border-left m-4 pl-4">
                  <%= link_to "Profil de l'aidant", profile_path(booking.helper), class: "btn seko-button" %>
                </div>
                <div class="missions">
                <%= render :partial => "favoris", locals: { booking: booking, helpers: @favoris_helper, path: "dashboard" } %>
                </div>
              </div>
                <% end %>
                <% end %>
        </div>
      </div>
    </div>
  </div>
</div>